package S120;

import java.awt.Container;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import static java.util.Collections.list;
import javax.swing.DefaultListModel;
import javax.swing.JButton;
import javax.swing.JList;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.plaf.basic.BasicListUI;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

public class EditTree extends javax.swing.JFrame {
    
    String sports[] = {"basketball", "soccer", "football","volleyball","tennis"};
    String foods[] = {"cake","rice","noodle","bread","fish","meat"};
    String drinks[] = {"coffee","water","juice","orange","lemon"};
    
    DefaultMutableTreeNode root = new DefaultMutableTreeNode("JTree");
    DefaultMutableTreeNode sport = new DefaultMutableTreeNode("sports");
    DefaultMutableTreeNode food = new DefaultMutableTreeNode("foods");
    DefaultMutableTreeNode drink = new DefaultMutableTreeNode("drinks");

    public EditTree() {
        initComponents(); 
        //Thiet lap du lieu cho tree
        root.add(sport);
        sport.add(new DefaultMutableTreeNode(sports[0]));
        sport.add(new DefaultMutableTreeNode(sports[1]));
        sport.add(new DefaultMutableTreeNode(sports[2]));
        root.add(food);
        food.add(new DefaultMutableTreeNode(foods[0]));
        food.add(new DefaultMutableTreeNode(foods[1]));
        food.add(new DefaultMutableTreeNode(foods[2]));
        root.add(drink);
        drink.add(new DefaultMutableTreeNode(drinks[0]));
        drink.add(new DefaultMutableTreeNode(drinks[1]));
        drink.add(new DefaultMutableTreeNode(drinks[2]));
        DefaultTreeModel treeModel = new DefaultTreeModel(root);      
        this.tree.setModel(treeModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();
        jScrollPane2 = new javax.swing.JScrollPane();
        tree = new javax.swing.JTree();
        panel = new javax.swing.JPanel();

        jScrollPane1.setViewportView(jTree1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Edit tree node");

        tree.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                treeMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tree);

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE)
                    .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void treeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_treeMouseClicked
        DefaultMutableTreeNode selectedNode;
        DefaultMutableTreeNode parentNode = null;
        try{
            selectedNode = (DefaultMutableTreeNode)tree.getSelectionPath().getLastPathComponent();
            parentNode = (DefaultMutableTreeNode)selectedNode.getParent();
            switch(parentNode.getUserObject().toString()){
                case "sports":
                    JList list = new JList(sports);
                    list.setBounds(0, 0, 80, tree.getHeight()-100);
                    JButton btn = new JButton("OK");
                    btn.setBounds(0, tree.getHeight()-100, 80, 30);
                    panel.add(list);
                    panel.add(btn);
                    panel.updateUI();
                    btn.addActionListener(new ActionListener() {
                        @Override
                        public void actionPerformed(ActionEvent e) {
                            selectedNode.setUserObject(list.getSelectedValue().toString());
                            tree.clearSelection();
                            panel.remove(list);
                            panel.remove(btn);
                            panel.updateUI();
                        }
                    });
                    break;
                case "foods":
                    list = new JList(foods);
                    list.setBounds(0, 0, 80, tree.getHeight()-100);
                    btn = new JButton("OK");
                    btn.setBounds(0, tree.getHeight()-100, 80, 30);
                    panel.add(list);
                    panel.add(btn);
                    panel.updateUI();
                    btn.addActionListener(new ActionListener() {
                        @Override
                        public void actionPerformed(ActionEvent e) {
                            selectedNode.setUserObject(list.getSelectedValue().toString());
                            tree.clearSelection();
                            panel.remove(list);
                            panel.remove(btn);
                            panel.updateUI();
                        }
                    });                    
                    break;
                case "drinks":
                    list = new JList(drinks);
                    list.setBounds(0, 0, 80, tree.getHeight()-100);
                    btn = new JButton("OK");
                    btn.setBounds(0, tree.getHeight()-100, 80, 30);
                    panel.add(list);
                    panel.add(btn);
                    panel.updateUI();
                    btn.addActionListener(new ActionListener() {
                        @Override
                        public void actionPerformed(ActionEvent e) {
                            selectedNode.setUserObject(list.getSelectedValue().toString());
                            tree.clearSelection();
                            panel.remove(list);
                            panel.remove(btn);
                            panel.updateUI();
                        }
                    });
                    break;
            }
        } catch(Exception ex){}     
    }//GEN-LAST:event_treeMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditTree.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditTree.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditTree.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditTree.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditTree().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTree jTree1;
    private javax.swing.JPanel panel;
    private javax.swing.JTree tree;
    // End of variables declaration//GEN-END:variables
}
