package edu.poly.entities;
// Generated Oct 30, 2020 11:10:05 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Classes generated by hbm2java
 */
@Entity
@Table(name="Classes"
    ,schema="dbo"
    ,catalog="tekeWeb"
)
public class Classes  implements java.io.Serializable {


     private String classId;
     private String name;
     private Set<Students> studentses = new HashSet<Students>(0);

    public Classes() {
    }

	
    public Classes(String classId) {
        this.classId = classId;
    }
    public Classes(String classId, String name, Set<Students> studentses) {
       this.classId = classId;
       this.name = name;
       this.studentses = studentses;
    }
   
     @Id 

    
    @Column(name="ClassId", unique=true, nullable=false, length=5)
    public String getClassId() {
        return this.classId;
    }
    
    public void setClassId(String classId) {
        this.classId = classId;
    }

    
    @Column(name="Name")
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="classes")
    public Set<Students> getStudentses() {
        return this.studentses;
    }
    
    public void setStudentses(Set<Students> studentses) {
        this.studentses = studentses;
    }




}


